### ISSUE TITLE
Add menus to title bar

### ISSUE THREAD

**Issue by hereisnaman** [coding-blocks/ide#277] opened 2020-05-15 20:02 UTC
There are so many buttons in the title bar, which do not fit on small screens and also creates a lot of noise. 

Lets categorize the options and create different menus for them.
```
1 Run Button
2 Language Selector
3 Input
4 File
   4.1 New
   4.2 Save
   4.3 Upload
   4.4 Download
5 Settings
6 Share
7 Shortcuts
8 Username
  8.1 saved codes
  8.2 logout
```

**Comment by dhwaj1902** [comment] 2020-05-15 20:18
I am currently working on this please assign this to me.

**Comment by hereisnaman** [comment] 2020-05-15 20:23
Sure

**Comment by sahuaman83** [comment] 2020-05-15 20:28
Can i work on this issue?

**Comment by amzamani** [comment] 2020-05-15 22:53
Please assign this to me, i have worked on this type of problems.

**Comment by rational-kunal** [comment] 2020-05-16 03:42
I was working on #177, so I have some initial code (dropdown for file) that would help me out in this issue. I would also like to work on this issue.

**Comment by hereisnaman** [comment] 2020-05-16 04:25
The best solution will be merged. Anyone can work on this.

**Comment by zoyron** [comment] 2020-05-16 08:35
@hereisnaman is it applicable to every issue that the best solution will be merged? Or only from the person to whom the issue is assigned?

**Comment by hereisnaman** [comment] 2020-05-16 10:34
@zoyron Yes the issues are open for anyone to work at. Only in the case of conflict if the timing and quality of the solutions are same, then the claiming it first will be taken into consideration.

**Comment by dakshkhetan** [comment] 2020-05-16 17:48
@hereisnaman Hey, I have also worked on this issue. Please review PR #291 😀

**Comment by paras151** [comment] 2020-05-17 04:49
When i run the command 'npm run dev' , it just shows a blank page at localhost:8080.
What could be the problem , or am i missing anything?

![Screenshot from 2020-05-17 09-17-47](https://user-images.githubusercontent.com/47773353/82135873-4fe76c80-9825-11ea-803c-2bbb0f6e5507.png)

**Closed** 2020-05-17 18:17 UTC
Labels: BOSS, BOUNTY: 500
